### PR TITLE
Feedback

### PR DESCRIPTION
**Pull request by SeanVSheep**
Hey @michaelbradymahoney  Could you take a look at my week 6 prac and see if there is anything you'd improve upon

### CODE REVIEW

**Comment by SarahWiese** [comment]
Hi Sean

I've actually withdrawn from CP1404. I've advised Lindsay so please contact him for someone else to review your prac.

Sarah
________________________________

**Comment by SeanVSheep** [comment]
Hey @michaelbradymahoney Could you take a look at my week 6 prac and see if there is anything you'd improve upon

**Comment by SeanVSheep** [comment]
Hey @michaelbradymahoney  Could you take a look at my week 6 prac and see if there is anything you'd improve upon

**Comment by lindsaymarkward** [comment]
@michealbradymahoney - thanks for reviewing Sean's PR (now that Sarah is not in the subject).

**Pull request merged**
